
datasource:
  dynamic: true
  type: dynamic

# DynamicDataSourceAutoConfiguration
spring:
  datasource:
    dynamic:
      primary: mysql-test #设置默认的数据源或者数据源组,默认值即为master
      strict: true #严格匹配数据源,默认false. true未匹配到指定数据源时抛异常,false使用默认数据源
      datasource:
        mysql-test:
          url: jdbc:mysql://192.168.101.128:3306/sibyl?useSSL=false&useUnicode=true&autoReconnect=true&serverTimezone=Asia/Shanghai
          username: root
          password: 123456
          driver-class-name: com.mysql.cj.jdbc.Driver
        postgresql-test:
          url: jdbc:postgresql://192.168.101.128:5432/sibyl_postgres?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf8&characterSetResults=utf8&useSSL=false&allowMultiQueries=true
          username: postgres
          password: 123456
          driver-class-name: org.postgresql.Driver
  redis:
    host: ${remote-server.ip}
    port: 6379
    database: 0
#    password:
mybatis-plus:
  configuration:
    #    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    log-impl: org.apache.ibatis.logging.nologging.NoLoggingImpl
  mapper-locations: classpath*:/mapper/**/*.xml


pagehelper:
  helperDialect: mysql
  reasonable: true
  supportMethodsArguments: true
  params: count=countSql