
server:
  port: 8080
  shutdown: graceful
spring:
  application:
    name: spring-boot-2x
  profiles:
    active: dev
    include: single-data
#    include: dynamic-datasource
  main:
    lazy-initialization: false
  thymeleaf:
    prefix: classpath:/static/
    suffix: .html
    cache: false
  devtools:
    livereload:
      enabled: true
    restart:
      additional-exclude: static/**

runnerEnabled: true
auth: false

debug: false
logging:
  level:
    me.sibyl: debug
    root: info
  file:
    name: ${spring.application.name}/log/${spring.application.name}.log
  logback:
    rollingpolicy:
      max-file-size: 100MB
      max-history: 360

remote-server:
#  ip: 127.0.0.1
  ip: 192.168.106.128

url:
  anonymous: /home/**,/auth/no/required,/hello/**