
server:
  port: 80
spring:
  application:
    name: spring-boot-2x
  profiles:
    active: dev
    include: single-data
  main:
    lazy-initialization: false

debug: false
logging:
  level:
    me.sibyl: debug
    root: info
  file:
    name: ${spring.application.name}/log/${spring.application.name}.log