
server:
  port: 80
  shutdown: graceful
spring:
  application:
    name: spring-boot-2x
  profiles:
    active: dev
    include: single-data
#    include: dynamic-datasource
  main:
    lazy-initialization: false
  thymeleaf:
    prefix: classpath:/static/
    suffix: .html
    cache: false

runnerEnabled: true
auth: false

debug: false
logging:
  level:
    me.sibyl: debug
    root: info
  file:
    name: ${spring.application.name}/log/${spring.application.name}.log

url:
  anonymous: /home/**,/auth/no/required,/hello/**