# 端口
server:
  port: 80

spring:
  application:
    name: sibyl-gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: gateway_route
          uri: http://localhost:9102
          predicates:
            - Path=/app/test

eureka:
  client:
    serviceUrl: #注册中心的注册地址
      defaultZone: http://127.0.0.1:8761/eureka/

