-- drop table T_SYS_USER if exists;
create table IF NOT EXISTS T_SYS_USER
(
    id              bigint generated by default as identity,
    username        varchar(255),
    nickname        varchar(255),
    password        varchar(255),
    phone_number    varchar(255),
    last_login_time TIMESTAMP,
    is_deleted      BOOLEAN not null default false,
    create_time     TIMESTAMP,
    create_id       bigint,
    update_time     TIMESTAMP,
    update_id       bigint,
    primary key (id)
);
-- drop table T_BASE_DATABASE if exists;
create table IF NOT EXISTS T_BASE_DATABASE
(
    id          bigint generated by default as identity,
    name        varchar(255),
    type        varchar(255),
    host        varchar(255),
    port        varchar(255),
    username    varchar(255),
    password    varchar(255),
    database    varchar(255),
    version     int              default 0,
    is_deleted  BOOLEAN not null default false,
    create_time TIMESTAMP,
    create_id   bigint,
    primary key (id)
);
create table IF NOT EXISTS T_SYS_CONFIG
(
    id          bigint generated by default as identity,
    name        varchar(255),
    code        varchar(255),
    value_      varchar(11024),
    desc        varchar(255),
    version     int              default 0,
    is_deleted  BOOLEAN not null default false,
    create_time TIMESTAMP,
    create_id   bigint,
    primary key (id)
);