-- drop table T_SYS_USER if exists;
create table IF NOT EXISTS T_SYS_USER
(
    id              bigint generated by default as identity,
    username        varchar(255),
    nickname        varchar(255),
    password        varchar(255),
    phone_number    varchar(255),
    last_login_time TIMESTAMP,
    is_deleted      BOOLEAN not null default false,
    create_time     TIMESTAMP,
    create_id       bigint,
    update_time     TIMESTAMP,
    update_id       bigint,
    primary key (id)
);
-- drop table T_BASE_DATABASE if exists;
create table IF NOT EXISTS T_BASE_DATABASE
(
    id          bigint generated by default as identity,
    name        varchar(255),
    type        varchar(255),
    host        varchar(255),
    port        varchar(255),
    username    varchar(255),
    password    varchar(255),
    database    varchar(255),
    version     int              default 0,
    is_deleted  BOOLEAN not null default false,
    create_time TIMESTAMP,
    create_id   bigint,
    primary key (id)
);
create table IF NOT EXISTS T_SYS_CONFIG
(
    id          bigint generated by default as identity,
    name        varchar(255),
    code        varchar(255),
    value_      varchar(1024),
    desc        varchar(255),
    version     int              default 0,
    is_deleted  BOOLEAN not null default false,
    create_time TIMESTAMP,
    create_id   bigint,
    primary key (id)
);

create table IF NOT EXISTS T_SYS_ACTION_LOG
(
    id            bigint generated by default as identity,
    topic         varchar(255),
    type          varchar(16),
    class         varchar(255),
    method        varchar(255),
    url           varchar(255),
    ip            varchar(64)      DEFAULT NULL,
    request_json  json,
    response_json json,
    body_json     json,
    throwable     json,
    is_deleted    BOOLEAN not null default false,
    create_time   TIMESTAMP,
    create_id     bigint,
    primary key (id)
);


create table IF NOT EXISTS T_BASE_LOCK_BOX
(
    id          bigint generated by default as identity,
    code        varchar(255),
    value       varchar(255),
    desc        varchar(255),
    is_deleted  varchar(1) not null default '0',
    create_time TIMESTAMP,
    create_id   bigint,
    update_time TIMESTAMP,
    update_id   bigint,
    primary key (id)
);

create table IF NOT EXISTS T_BASE_FILE
(
    ID            BIGINT auto_increment
        primary key,
    FILE_NAME     CHARACTER VARYING(255),
    TYPE          CHARACTER VARYING(64),
    ABSOLUTE_PATH CHARACTER VARYING(1024),
    relative_path CHARACTER VARYING(1024),
    SIZE          long,
    SUFFIX        CHARACTER VARYING(64),
    SERIAL_NUMBER CHARACTER VARYING(255),
    SHA256        CHARACTER VARYING(64),
    CODE          CHARACTER VARYING(64),
    WIDTH         integer,
    HEIGHT        integer,
    IS_DELETED    CHARACTER VARYING(2) default '0' not null,
    CREATE_TIME   TIMESTAMP,
    CREATE_ID     BIGINT,
    UPDATE_TIME   TIMESTAMP,
    UPDATE_ID     BIGINT
);