snaker:
  flow:
    auto-init-schema: false       #是否初始化数据库脚本，默认为false
    db-access-type: mybatis_plus  #sql执行器类型 可选 jdbc、spring、mybatis_plus。默认为jdbc
    expression-type: juel         #决策表达式类型 可选juel和spel。默认为juel
    cache:
      cache-type: redis #缓存类型 可选内存、ehcache、redis

# 缓存类型为redis情况下，如下属性可进行配置
#spring:
#  cache:
#    type: redis
#    redis:
#      key-prefix: "snaker::"
#      time-to-live: 1h