app:
  key: sibyl-kotlin

runnerEnabled: true
auth: false
isDev: true
logDetail: false


server:
  port: 80
  shutdown: graceful
  tomcat:
    connection-timeout: 3600000
spring:
  application:
    name: kotlin-runner
  profiles:
    active: dev
    include: db, quartz
  main:
    keep-alive: true
  threads:
    virtual:
      enabled: true
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
#  security:
#    strategy: MODE_INHERITABLETHREADLOCAL
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
    cache: false
  devtools:
    livereload:
      enabled: false
    restart:
      exclude: logs/**
      enabled: false
  r2dbc:
    url: r2dbc:h2:file:///E:/sibyl-system/database/h2/sibyl;AUTO_SERVER=TRUE;MODE=LEGACY;NON_KEYWORDS=VALUE;USER=sibyl;PASSWORD=sibyl-h2-2023
    pool:
      enabled: true
      max-size: 1024
      min-idle: 64
      initial-size: 64
  h2:
    console:
      enable: true
      path: /h2-console
      settings:
        web-allow-others: true
  data:
    redis:
      host: 127.0.0.1
      port: 6379
      database: 0
      repositories:
        enabled: false
  info:
    env:
      enabled: true


file:
  path: ./${spring.application.name}/file

debug: false
logging:
  level:
    root: info
    org.springframework.r2dbc: info
    io.asyncer.r2dbc.mysql.client.ReactorNettyClient: warn
  file:
    name: ./${spring.application.name}/logs/log.log #这里因为是内部module就多加一层文件夹
  logback:
    rollingpolicy:
      max-file-size: 100MB
      max-history: 360




data-source:
  sibyl-mysql:
    driver: mysql
    host: 127.0.0.1
    port: 3306
    database: sibyl
    user: root
    password: 123456
  sibyl-postgresql:
    driver: postgresql
    host: 127.0.0.1
    port: 3306
    database: postgres
    user: postgres
    password: 123456

