
server-ip: 127.0.0.1

bio:
  enable: false
  server-ip: ${server-ip}
  server-port: 11081

nio:
  enable: false
  server-ip: ${server-ip}
  server-port: 11081

netty:
  enable: false
  server-ip: ${server-ip}
  server-port: 11091
  bossThreadNum: 2

tcp:
  enable: true
  server-ip: ${server-ip}
  server-port: 11111

http:
  enable: false
  server-ip: ${server-ip}
  server-port: 8081

socket:
  enable: false
  server-ip: ${server-ip}
  server-port: 8082

mqtt:
  enable: false
  server-ip: ${server-ip}
  server-port: 1883
