
server:
  port: 8080
  shutdown: graceful
spring:
  application:
    name: iot-server
  profiles:
    active: dev
    include: server
  devtools:
    livereload:
      enabled: true
    restart:
      additional-exclude: static/**

runnerEnabled: true
auth: false

debug: false
logging:
  level:
    me.sibyl: debug
    root: info
  file:
    name: ${spring.application.name}/log/${spring.application.name}.log
  logback:
    rollingpolicy:
      max-file-size: 100MB
      max-history: 360

remote-server:
  #  ip: 127.0.0.1
  ip: 192.168.101.128
