
server:
  port: 9101  #服务端口号
spring:
  application:
    name: sibyl-eureka-service-consumer #服务名称--调用的时候根据名称来调用该服务的方法
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/sibyl?useSSL=false&useUnicode=true&autoReconnect=true&serverTimezone=Asia/Shanghai
    username: root
    password: 123456
  redis:
    host: 127.0.0.1
    port: 6379
    database: 0
  main:
    allow-bean-definition-overriding: true
    allow-circular-references: true
#    password:
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  mapper-locations: classpath*:/mapper/**/*.xml

eureka:
  instance:
    prefer-ip-address: true
    instance-id: ${spring.cloud.client.ip-address}:${server.port}
  client:
    serviceUrl: #注册中心的注册地址
      defaultZone: http://127.0.0.1:8761/eureka/
#    register-with-eureka: false
#    registry-fetch-interval-seconds: 10

#seata:
#  enabled: true
#  application-id: ${spring.application.name}
#  tx-service-group: sibyl_eureka_tx_group
#  service:
#    vgroup-mapping:
#      sibyl_eureka_tx_group: seata-server # 找到seata集群中名为"seata-server"的application
#  registry:
#    type: eureka # 注册中心为eureka
#    eureka:
#      application: ${spring.application.name}
#      service-url: http://127.0.0.1:8761/eureka/

feign:
  circuitbreaker:
    enabled: true
  hystrix:
    enabled: false
    client:
      config:
        default:
          connect-timeout: 300000
          read-timeout: 300000
