
server:
  port: 10001

spring:
  profiles:
    active: dev
  application:
    name: sibyl-reactive-app
  r2dbc:
    url: r2dbc:mysql://localhost:3306/sibyl?useSSL=false&useUnicode=true&autoReconnect=true&serverTimezone=GMT%2B8&SSL=false&sslMode=DISABLED
    username: root
    password: 123456
    pool:
      enabled: true
      initial-size: 10
      max-size: 100

