server:
  port: 8080
  shutdown: graceful
spring:
  application:
    name: sibyl-server
  profiles:
    active: dev
    include: db
  main:
    lazy-initialization: false
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
    cache: false

debug: false
logging:
  level:
    me.sibyl: debug
    root: info
#    org:
#      springframework:
#        security: DEBUG
  file:
    name: log/${spring.application.name}.log
  logback:
    rollingpolicy:
      max-file-size: 100MB
      max-history: 360
