drop table T_DATABASE if exists;
create table IF NOT EXISTS T_DATABASE(
    id bigint generated by default as identity,
    name varchar(255),
    type varchar(255),
    version int,
    create_time TIMESTAMP,
    primary key(id)
);
